### ISSUE TITLE
Excluded JTReg test: java/lang/StackTraceElement/PublicConstructor.java

### ISSUE THREAD

**Issue by M-Davies** [ibmruntimes/openj9-openjdk-jdk11#200]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
Test fails on all OS's for jdk11-openj9 due to an ```assertEquals()``` fail

```STDERR:
10:49:12  java.lang.RuntimeException: Expected: app/jdk.module@9.0/com.acme.Widget.frobnicate(Widget.java:42) but found: jdk.module/com.acme.Widget.frobnicate(Widget.java:42)
10:49:12  	at PublicConstructor.assertEquals(PublicConstructor.java:92)
10:49:12  	at PublicConstructor.testConstructorWithModule(PublicConstructor.java:86)
10:49:12  	at PublicConstructor.main(PublicConstructor.java:36)
10:49:12  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:49:12  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:49:12  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:49:12  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:49:12  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
10:49:12  	at java.base/java.lang.Thread.run(Thread.java:831)
10:49:12  
10:49:12  JavaTest Message: Test threw exception: java.lang.RuntimeException
```

--------------------------------------------------------------------------------------------
The issue is within `printStackTraceElement()` which is called when `toString()` is called in the test. See code below:
```
public static void printStackTraceElement(StackTraceElement e, Object elementSource, Appendable buf, boolean extended) {
	final java.lang.String modName = e.getModuleName();
	if (null != modName) {
		appendTo(buf, modName);
		if (extended) {
			String mVer = e.getModuleVersion();
			if (null != mVer) {
				appendTo(buf, "@"); //$NON-NLS-1$
				appendTo(buf, mVer);
			}
		}
		appendTo(buf, "/"); //$NON-NLS-1$
	} else if (extended) {
		appendTo(buf, "app//"); //$NON-NLS-1$
	}
```
The issue is with the module version, which doesn't get executed due to the extended boolean being declared as false in the `StackTraceElement` class. See code below:
```
public String toString() {
	StringBuilder buf = new StringBuilder(80);
	Util.printStackTraceElement(this, source, buf, false);
	return buf.toString();
```
Attempting to induce a true value to the `extended` variable to test compatibility with the test
--------------------------------------------------------------------------------------------
It appears the `StackTraceElement.class` above was a compiler generated file and as such, can't be edited. The actual method used by the compiler is:
```
@Override
            public String toString() {
                String mid = getClassLoaderName(c);
                Module module = c.getModule();
                if (module.isNamed()) {
                    ModuleDescriptor md = module.getDescriptor();
                    mid = md.name();
                    if (md.version().isPresent())
                        mid += "@" + md.version().get().toString();
                    mid += "/";
                }
                String fileName = getFileName();
                int lineNumber = getLineNumber();
                String sourceinfo = "Unknown Source";
                if (isNativeMethod()) {
                    sourceinfo = "Native Method";
                } else if (fileName != null && lineNumber >= 0) {
                    sourceinfo = fileName + ":" + lineNumber;
                }
                return String.format("%s/%s.%s(%s)", mid, getClassName(), getMethodName(),
                                     sourceinfo);
```

**Comment by M-Davies** [comment]
Issue raised on openj9 github https://github.com/eclipse/openj9/issues/6659
