### ISSUE TITLE
Regression failure seen: Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases29.dat

### ISSUE THREAD

**Issue by adamfarley** [ibmruntimes/openj9-openjdk-jdk11#411]
Error message seen during a JDK11 OpenJ9 build:

```
Generating DDR pointer and structure class files
Exception in thread "main" java.lang.RuntimeException: Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases29.dat - cannot continue
	at com.ibm.j9ddr.StructureReader.loadAliasMapData(StructureReader.java:438)
	at com.ibm.j9ddr.StructureReader.loadAliasMap(StructureReader.java:306)
	at com.ibm.j9ddr.StructureReader.applyAliases(StructureReader.java:222)
	at com.ibm.j9ddr.StructureReader.<init>(StructureReader.java:120)
	at com.ibm.j9ddr.tools.ClassGenerator.readBlob(ClassGenerator.java:93)
	at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:174)
	at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:79)
```

Link: https://github.com/adamfarley/build-jdk/runs/2722774171?check_suite_focus=true

This error appears to be a regression for [this issue](https://github.com/eclipse-openj9/openj9/issues/12249), which is supported by the fact that the [fix](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/394) now appears to be missing from the [relevant file](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/DDR.gmk).

@keithc-ca - Do you know if this fix was removed deliberately?

**Comment by sophia-guo** [comment]
This is probably same issue happened to build-openj9.  As jdk11 need a recent jdk11 boot JVM. @adamfarley  using a latest jdk11 may solve this.  We recently discovered you need a recent jdk11 boot JVM for this to work. https://github.com/eclipse-openj9/build-openj9/issues/25

**Comment by adamfarley** [comment]
Thanks Sophia. I didn't know about that issue. I'll give that workaround a shot.

I think this issue should stay open, however, as Keith had a fix for this problem back in March. It allowed successful JDK11 OpenJ9 builds using a JDK10 boot JDK, and I'm not clear on whether the removal of that fix was accidental.

Will see what Keith says.

**Comment by adamfarley** [comment]
Ah, NVM. Peter Shipton says it's not a priority. Closing.

https://openj9.slack.com/archives/C8312LCV9/p1622728153046400?thread_ts=1622726350.046100&cid=C8312LCV9
